import { IFlowDefinition } from '@cqlab/cqflow-core';

export const hypertensionDef = {
  id: '30bf7802-bbdd-4385-93d6-721e568891aa',
  createdAt: '2023-10-13T19:58:53.516Z',
  bindId: 'docs-hypertension',
  version: '0.0.1',
  type: 'NonInteractive',
  nodes: {
    end_eifuphxf: {
      id: 'end_eifuphxf',
      label: 'End',
      bindId: 'end_eifuphxf',
      nodeType: 'End',
      position: {
        x: 893.2815040613492,
        y: 373.1827340518704,
        width: 60,
        height: 60,
      },
    },
    start_xenjpdkh: {
      id: 'start_xenjpdkh',
      next: {
        id: 'narrative_cmnlwnrw',
        type: 'Unary',
        toHandle: 'top',
        fromHandle: 'bottom',
      },
      label: 'Start',
      bindId: 'start_xenjpdkh',
      nodeType: 'Start',
      position: {
        x: 287.025102331974,
        y: -610.8504531577094,
        width: 60,
        height: 60,
      },
    },
    emitdata_cagljqpe: {
      id: 'emitdata_cagljqpe',
      next: {
        id: 'end_eifuphxf',
        type: 'Unary',
        toHandle: 'top',
        fromHandle: 'right',
      },
      label: 'Hypertensive crisis (consult your doctor immediately)',
      bindId: 'emitdata_cagljqpe',
      nodeType: 'EmitData',
      position: {
        x: 534.172361541594,
        y: -79.74099651990281,
        width: 210,
        height: 96,
      },
    },
    emitdata_gjuoguwp: {
      id: 'emitdata_gjuoguwp',
      next: {
        id: 'end_eifuphxf',
        type: 'Unary',
        toHandle: 'left',
        fromHandle: 'right',
      },
      label: 'Blood pressure is elevated',
      bindId: 'emitdata_gjuoguwp',
      nodeType: 'EmitData',
      position: {
        x: 558.5420498211245,
        y: 533.64521907911,
        width: 168,
        height: 83,
      },
    },
    emitdata_kzxydbxo: {
      id: 'emitdata_kzxydbxo',
      next: {
        id: 'end_eifuphxf',
        type: 'Unary',
        toHandle: 'left',
        fromHandle: 'right',
      },
      label: 'Hypertension Stage II',
      bindId: 'emitdata_kzxydbxo',
      nodeType: 'EmitData',
      position: {
        x: 548.0070338655897,
        y: 136.3415685456883,
        width: 174,
        height: 82,
      },
    },
    emitdata_wmoedazh: {
      id: 'emitdata_wmoedazh',
      next: {
        id: 'end_eifuphxf',
        type: 'Unary',
        toHandle: 'bottom',
        fromHandle: 'right',
      },
      label: 'Blood Pressure is Normal',
      bindId: 'emitdata_wmoedazh',
      nodeType: 'EmitData',
      position: {
        x: 563.8251487525131,
        y: 694.5812878043153,
        width: 183,
        height: 78,
      },
    },
    emitdata_yhdcpzyt: {
      id: 'emitdata_yhdcpzyt',
      next: {
        id: 'end_eifuphxf',
        type: 'Unary',
        toHandle: 'left',
        fromHandle: 'right',
      },
      label: 'Hypertension Stage I',
      bindId: 'emitdata_yhdcpzyt',
      nodeType: 'EmitData',
      position: {
        x: 554.3805782021981,
        y: 360.10378363513166,
        width: 165,
        height: 87,
      },
    },
    logictree_tkbrlcbu: {
      id: 'logictree_tkbrlcbu',
      next: {
        type: 'Binary',
        trueId: 'emitdata_kzxydbxo',
        falseId: 'logictree_zdddgikg',
        trueToHandle: 'left',
        falseToHandle: 'top',
        trueFromHandle: 'right',
        falseFromHandle: 'bottom',
      },
      label: 'Check Hypertension Stage II',
      bindId: 'logictree_tkbrlcbu',
      nodeType: 'LogicTree',
      position: {
        x: 199.03326715375607,
        y: 107.02246996326477,
        width: 240,
        height: 142,
      },
      logicTree: {
        children: [
          {
            id: 'truefalse_cinedaqk',
            label: 'Systolic BP >= 140',
            bindId: 'systolic_bp_greater_equal_140',
            nodeType: 'TrueFalse',
            logicType: 'TrueFalseLeaf',
          },
          {
            id: 'truefalse_qxjeekkk',
            label: 'Diastolic >= 90',
            bindId: 'diastolic_bp_greater_equal_90',
            nodeType: 'TrueFalse',
            logicType: 'TrueFalseLeaf',
          },
        ],
        logicType: 'Or',
      },
    },
    logictree_wjistwqj: {
      id: 'logictree_wjistwqj',
      next: {
        type: 'Binary',
        trueId: 'emitdata_cagljqpe',
        falseId: 'logictree_tkbrlcbu',
        trueToHandle: 'left',
        falseToHandle: 'top',
        trueFromHandle: 'right',
        falseFromHandle: 'bottom',
      },
      label: 'Check Hypertensive Crisis',
      bindId: 'logictree_wjistwqj',
      nodeType: 'LogicTree',
      position: {
        x: 207.46927070021098,
        y: -100.48712751101758,
        width: 218,
        height: 141,
      },
      logicTree: {
        children: [
          {
            id: 'truefalse_eznltjnn',
            label: 'Systolic BP > 180',
            bindId: 'systolic_bp_greater_180',
            nodeType: 'TrueFalse',
            logicType: 'TrueFalseLeaf',
          },
          {
            id: 'truefalse_nfyyomng',
            label: 'Diastolic > 120',
            bindId: 'diastolic_greater_120',
            nodeType: 'TrueFalse',
            logicType: 'TrueFalseLeaf',
          },
        ],
        logicType: 'Or',
      },
    },
    logictree_zdddgikg: {
      id: 'logictree_zdddgikg',
      next: {
        type: 'Binary',
        trueId: 'emitdata_yhdcpzyt',
        falseId: 'truefalse_rxkushzi',
        trueToHandle: 'left',
        falseToHandle: 'top',
        trueFromHandle: 'right',
        falseFromHandle: 'bottom',
      },
      label: 'Check Hypretension Stage I',
      bindId: 'logictree_zdddgikg',
      nodeType: 'LogicTree',
      position: {
        x: 186.95533941953204,
        y: 335.97736909411867,
        width: 263,
        height: 141,
      },
      logicTree: {
        children: [
          {
            id: 'truefalse_kubuyhod',
            label: 'Systolic BP >= 130 and < 140',
            bindId: 'systolic_greater_equal_130_less_140',
            nodeType: 'TrueFalse',
            logicType: 'TrueFalseLeaf',
          },
          {
            id: 'truefalse_pslzjhrk',
            label: 'Diastolic BP >= 80 and < 90',
            bindId: 'diastolic_greater_equal_80_less_90',
            nodeType: 'TrueFalse',
            logicType: 'TrueFalseLeaf',
          },
        ],
        logicType: 'Or',
      },
    },
    narrative_cmnlwnrw: {
      id: 'narrative_cmnlwnrw',
      next: {
        id: 'customform_rcwrnyvk',
        type: 'Unary',
        toHandle: 'top',
        fromHandle: 'bottom',
      },
      label:
        'More information at https://www.heart.org/en/health-topics/high-blood-pressure/understanding-blood-pressure-readings',
      bindId: 'narrative_cmnlwnrw',
      nodeType: 'Narrative',
      position: {
        x: 114.96512572317499,
        y: -474.92541256504245,
        width: 403,
        height: 92,
      },
      narrative: '',
    },
    customform_rcwrnyvk: {
      id: 'customform_rcwrnyvk',
      next: {
        id: 'logictree_wjistwqj',
        type: 'Unary',
        toHandle: 'top',
        fromHandle: 'bottom',
      },
      label: 'Enter Systolic and Diastolic Blood Pressure',
      bindId: 'enter_blood_pressure_panel',
      nodeType: 'CustomForm',
      position: {
        x: 232.4952840618556,
        y: -292.7545787195696,
        width: 171,
        height: 97,
      },
    },
    truefalse_rxkushzi: {
      nodeType: 'TrueFalse',
      id: 'truefalse_rxkushzi',
      bindId: 'systolic_greater_equal_120_less_130',
      label: 'Systolic BP >= 120 and < 130',
      next: {
        type: 'Binary',
        trueId: 'emitdata_gjuoguwp',
        trueFromHandle: 'right',
        trueToHandle: 'left',
        falseId: 'emitdata_wmoedazh',
        falseFromHandle: 'right',
        falseToHandle: 'left',
      },
      position: {
        x: 257.04574889567596,
        y: 595.3221312412271,
        width: 128,
        height: 128,
      },
    },
  },
} as IFlowDefinition;
